### ISSUE TITLE
Publish to network - example

### ISSUE THREAD

**Issue by trozler** [ipfs/js-ipns#129]
Hi thanks for the great repo. 
I'm using the base of the repo to build an application that lets users publish data to IPNS, using their metamask to sign. 

I was wondering if you could help me answer the following:

1. Why does the IPNS entry data require two signatures?

2. Once I have created an IPNS entry record how do I send this entry to the network?
Assuming I'm running the [js-ipfs](https://github.com/ipfs/js-ipfs) module in the browser; is there an easy way to publish a custom signed entry?

**Comment by achingbrain** [comment]
> Why does the IPNS entry data require two signatures?

It currently supports v1 and v2 signatures.  At some point in the near future v1 will be retired and only v2 will be supported.

> Once I have created an IPNS entry record how do I send this entry to the network?

You need to either use [datastore-pubsub](https://github.com/ipfs/js-datastore-pubsub) to broadcast the record, or [libp2p-kad-dht](https://github.com/libp2p/js-libp2p-kad-dht) to store the record and answer requests for it.

> Assuming I'm running the js-ipfs module in the browser; is there an easy way to publish a custom signed entry?

Not via the core API, it just deals in the value to be published and the parameters to use in the sig, though you can roll your own version of the [ipns subsystem](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-core/src/ipns) to do it.

Sorry for the delay in replying - https://discuss.ipfs.io is usually a better venue for getting help than opening issues on this repo.
