### ISSUE TITLE
Generating IPNS ID with IPFS hash

### ISSUE THREAD

**Issue by jay0x5** [ipfs/js-ipns#155]
Hello, I know this is a pretty basic and dumb question but how do i actually generate an IPFS ID from my IPFS hash using this package? Would really appreciate if someone can help me since i tried to read the documentation but i failed to comprehend any of it.

**Comment by achingbrain** [comment]
See [create-record](https://github.com/ipfs/js-ipns#create-record) in the README and it's [usage in the tests](https://github.com/ipfs/js-ipns/blob/master/test/index.spec.ts#L27-L41).

The returned value is the IPNS record, the IPNS name used to resolve the record by other peers is `/ipns/{peerId}` where `{peerid}` is the peer ID used to create and sign the record.
