### ISSUE TITLE
(bug)signatureV1 vs signature 

### ISSUE THREAD

**Issue by DougAnderson444** [ipfs/js-ipns#217]
https://github.com/ipfs/js-ipns/blob/675aa64258154513bc014afb3f99bdfd13d5f167/src/pb/ipns.proto#L14

Isn't this supposed to be `signatureV1` in accordance with the [spec](https://specs.ipfs.tech/ipns/ipns-record/#record-serialization-format) and go-impl: 

https://github.com/ipfs/go-ipns/blob/72be64e27e743b828fe4eb8a721abd1b97610421/pb/ipns.proto#L13

**Comment by achingbrain** [comment]
The field name is not written into the protobuf, only the field number so this is compatible with go-ipns and isn't a bug in terms of behaviour, though it would be good to use the same field name as the spec.
